import { Platform, StyleSheet } from 'react-native';

import { colors } from './colors';

export const appSharedStyles = StyleSheet.create({
  containerBase: {
    backgroundColor: 'transparent',
    flex: 1,
    padding: 10,
  },
  containerFooter: {
    borderTopWidth: 1,
    borderTopColor: colors.borderSecondary,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  containerRowStart: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  containerRowCenter: {
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  containerHighlight: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderHighlight,
    borderRadius: 8,
    borderWidth: 1,
  },
  containerRowCentered: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  containerHeader: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  containerRowHeader: {
    alignItems: 'center',
    backgroundColor: colors.backgroundPrimary,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  containerPagination: {
    alignItems: 'center',
    borderTopColor: colors.borderSecondary,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  containerRowWrapped: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  containerHeaderSide: {
    minWidth: 60,
  },
  containerItemBordered: {
    backgroundColor: colors.backgroundGrey,
    borderColor: colors.borderSecondary,
    borderRadius: 6,
    borderWidth: 1,
    marginBottom: 5,
    padding: 10,
  },
  containerIconPreview: {
    alignItems: 'center',
    borderBottomColor: colors.borderSecondary,
    borderBottomWidth: 1,
    marginBottom: 15,
    paddingBottom: 15,
    width: '100%',
    gap: 10,
  },
  containerListContent: {
    paddingBottom: 5,
  },
  containerRowFull: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  containerPinDisplay: {
    alignItems: 'center',
    backgroundColor: colors.backgroundHighlight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderPrimary,
  },
  containerToggle: {
    flexDirection: 'row',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 6,
    overflow: 'hidden',
  },

  itemBordered: {
    flexGrow: 0,
    borderColor: colors.borderPrimary,
    borderWidth: 1,
    borderRadius: 5,
  },
  itemFlexCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemFlex: {
    flex: 1,
  },
  itemFull: {
    width: '100%',
  },
  itemOuter: {
    flex: 1,
    backgroundColor: 'transparent',
  },

  announcementDate: {
    color: colors.textVeryLight,
    fontSize: 12,
    marginTop: 8,
    textAlign: 'right',
  },
  announcementTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  assignedTaskActions: {
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  awardedPointsText: {
    color: colors.gold,
    fontSize: 20,
    fontWeight: 'bold',
  },
  balance: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  cannotAffordText: {
    color: colors.textLight,
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 2,
  },
  centeredView: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    flex: 1,
    justifyContent: 'center',
  },
  checkmark: {
    color: colors.primary,
    fontSize: 24,
    marginLeft: 10,
  },
  confirmationText: {
    fontSize: 16,
    lineHeight: 22,
    marginVertical: 15,
    textAlign: 'center',
  },
  contentArea: {
    flex: 1,
  },
  contentScrollView: {
    marginBottom: 15,
    maxHeight: '65%',
    width: '100%',
  },
  currentGoalItem: {
    backgroundColor: colors.backgroundHighlight,
    borderColor: colors.primary,
    borderWidth: 2,
  },
  emptyListText: {
    color: colors.textLight,
    fontStyle: 'italic',
    marginTop: 5,
    textAlign: 'center',
  },
  filterLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 10,
  },
  filterSection: {
    backgroundColor: colors.backgroundPrimary,
    borderBottomColor: colors.borderSecondary,
    borderBottomWidth: 1,
    paddingBottom: 10,
    width: '100%',
  },
  footer: {
    color: colors.textSecondary,
    fontSize: 16,
    marginBottom: 10,
    marginTop: 20,
    textAlign: 'center',
  },
  footerButton: {
    marginTop: 10,
    width: '100%',
  },
  goalImage: {
    borderColor: colors.borderSecondary,
    borderRadius: 4,
    borderWidth: 1,
    height: 50,
    width: 50,
  },
  goalSelectDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  goalSelectImage: {
    borderColor: colors.borderSecondary,
    borderRadius: 4,
    borderWidth: 1,
    height: 45,
    marginRight: 12,
    width: 45,
  },
  goalSelectItem: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderSecondary,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  goalSelectItemContent: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  goalSelectName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 2,
  },
  goalText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  header: {
    color: colors.textPrimary,
    flexShrink: 1,
    fontSize: 22,
    fontWeight: 'bold',
  },
  headerTitle: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 22,
    fontWeight: 'bold',
    marginHorizontal: 5,
    textAlign: 'center',
  },
  hidden: {
    display: 'none',
  },
  historyItemAmount: {
    fontWeight: 'bold',
  },
  historyItemDetails: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  historyItemNotes: {
    color: colors.textLight,
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 4,
  },
  historyItemTimestamp: {
    color: colors.textVeryLight,
    fontSize: 12,
    marginBottom: 4,
  },
  iconPreview: {
    width: 80,
    height: 80,
    marginBottom: 5,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
    backgroundColor: colors.backgroundGrey,
  },
  inactiveItem: {
    borderColor: colors.secondary,
    opacity: 0.7,
  },
  itemContentRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 10,
  },

  inactiveItemStyle: {
    borderColor: colors.secondary,
    opacity: 0.7,
  },
  input: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderPrimary,
    borderRadius: 5,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 16,
    marginBottom: 15,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: '100%',
  },
  instrumentIcon: {
    height: 40,
    marginRight: 15,
    width: 40,
  },
  instrumentText: {
    color: colors.textSecondary,
    fontSize: 16,
    marginBottom: 5,
  },
  itemActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  itemDetailText: {
    color: colors.textSecondary,
    fontSize: 13,
    marginBottom: 2,
  },
  itemImageMedium: {
    borderColor: colors.borderPrimary,
    borderRadius: 4,
    borderWidth: 1,
    height: 60,
    marginRight: 15,
    width: 60,
  },
  itemTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  itemTitleText: {
    flexShrink: 1,
    marginBottom: 0,
  },
  label: {
    alignSelf: 'flex-start',
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
    width: '100%',
  },
  listArea: {
    marginTop: 10,
  },
  listItem: {
    borderBottomColor: colors.borderSecondary,
    borderBottomWidth: 1,
    padding: 12,
  },
  listItemText: {
    color: colors.textPrimary,
    fontSize: 15,
  },
  loadingText: {
    color: colors.textSecondary,
    fontSize: 14,
    marginLeft: 10,
  },
  modalContextInfo: {
    color: colors.textSecondary,
    fontSize: 15,
    marginBottom: 10,
    textAlign: 'center',
    width: '100%',
  },
  modalHeader: {
    alignItems: 'center',
    backgroundColor: colors.backgroundPrimary,
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    padding: 15,
    width: '100%',
  },
  listItemFull: {
    flexGrow: 0,
    marginBottom: 15,
    maxHeight: '60%',
    width: '100%',
  },
  modalMessage: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 21,
    marginBottom: 25,
    textAlign: 'center',
  },
  modalSectionTitle: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
    marginTop: 15,
    textAlign: 'center',
    width: '100%',
  },
  modalSubSection: {
    borderTopColor: colors.borderSecondary,
    borderTopWidth: 1,
    marginTop: 20,
    paddingTop: 15,
    width: '100%',
  },
  modalTitle: {
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    paddingBottom: 10,
    textAlign: 'center',
    width: '100%',
  },
  modalView: {
    alignItems: 'stretch',
    backgroundColor: colors.backgroundPrimary,
    borderRadius: 10,
    elevation: 5,
    margin: 20,
    maxHeight: '90%',
    maxWidth: 500,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    width: '90%',
  },
  pageInfo: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    marginHorizontal: 15,
  },
  parentHeader: {
    alignItems: 'center',
    backgroundColor: colors.backgroundPrimary,
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  parentHeaderText: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  pendingDetail: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 3,
  },
  pendingItem: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderWarning,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  pendingNote: {
    color: colors.warning,
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 5,
  },
  pendingTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  picker: {
    width: '100%',
    height: Platform.OS === 'android' ? 50 : undefined,
    color: colors.textPrimary,
  },
  pickerItem: {
    height: 120,
    fontSize: 16,
  },
  previewText: {
    color: colors.textLight,
    fontSize: 14,
    fontStyle: 'italic',
    marginBottom: 15,
    textAlign: 'center',
  },
  progressBarBackground: {
    backgroundColor: '#eee',
    borderRadius: 5,
    height: 10,
    marginBottom: 10,
    overflow: 'hidden',
  },
  progressBarFill: {
    borderRadius: 5,
    height: '100%',
  },
  progressText: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 5,
  },
  publicHeader: {
    fontSize: 28,
    marginBottom: 5,
    textAlign: 'center',
  },
  rangeText: {
    color: colors.textSecondary,
    flexDirection: 'row',
    fontSize: 12,
    justifyContent: 'space-between',
    marginBottom: 5,
    marginTop: -5,
    paddingHorizontal: 5,
    width: '100%',
  },
  rewardItemAffordable: {
    borderColor: colors.success,
    borderWidth: 2,
  },
  rewardItemGoal: {
    backgroundColor: colors.backgroundHighlight,
    borderColor: colors.primary,
    borderWidth: 2,
  },
  rewardName: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  roleSectionTitle: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  roleSpecificSection: {
    borderTopColor: colors.borderSecondary,
    borderTopWidth: 1,
    marginTop: 15,
    paddingTop: 15,
    width: '100%',
  },
  safeArea: {
    backgroundColor: 'transparent',
    flex: 1,
  },
  scrollView: {
    marginBottom: 15, // From commonSharedStyles
    width: '100%',
  },
  searchInput: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderPrimary,
    borderRadius: 5,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 16,
    marginBottom: 10,
    padding: 10,
    width: '100%',
  },
  sectionSubTitle: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    marginTop: 15,
  },
  sectionTitle: {
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    marginTop: 20,
    paddingBottom: 5,
  },
  separator: {
    backgroundColor: colors.borderSecondary,
    height: 1,
    marginVertical: 10,
  },
  slider: {
    height: 40,
    marginTop: 10,
    width: '100%',
  },
  stepTitle: {
    alignSelf: 'flex-start',
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
    marginTop: 10,
    width: '100%',
  },
  studentActions: {
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'space-around',
    marginTop: 10,
  },
  subTitle: {
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 15,
    paddingBottom: 10,
    textAlign: 'center',
    width: '100%',
  },
  subheader: {
    color: colors.textSecondary,
    fontSize: 18,
    marginBottom: 20, // From commonSharedStyles
    textAlign: 'center',
  },
  tabContentPlaceholder: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  taskDescription: {
    color: colors.textLight, // From commonSharedStyles
    fontSize: 12,
    marginTop: 3,
  },
  taskItem: {
    marginBottom: 8,
    padding: 10,
  },
  taskItemStatus: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 8,
  },
  taskItemText: {
    color: colors.textPrimary,
    fontSize: 14, // From commonSharedStyles
  },
  taskItemTickets: {
    color: colors.success,
    fontSize: 13,
    fontWeight: 'bold',
  },
  taskItemTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: 'bold',
    marginBottom: 3,
  },
  taskLibraryItemTickets: {
    color: colors.textSecondary,
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 5,
  },
  taskTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  teacherNav: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginBottom: 20,
  },
  textCenter: {
    textAlign: 'center',
  },
  textDanger: {
    // From commonSharedStyles
    color: colors.danger,
  },
  textGold: {
    color: colors.gold,
  },
  textSuccess: {
    color: colors.success,
  },
  textWarning: {
    color: colors.warning,
  },
  textArea: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderPrimary,
    borderRadius: 5,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 16,
    marginBottom: 15,
    minHeight: 80,
    paddingHorizontal: 10,
    paddingVertical: 8,
    textAlignVertical: 'top',
    width: '100%',
  },

  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  activeStatus: {
    fontWeight: 'bold',
    color: colors.success,
  },
  inactiveStatus: {
    fontWeight: 'bold',
    color: colors.secondary,
  },
  infoText: {
    fontSize: 12,
    color: colors.textLight,
    fontStyle: 'italic',
    marginTop: 2,
    marginLeft: 5,
  },

  linkedStudentItem: { backgroundColor: colors.backgroundSecondary },
  linkedStudentActions: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-start',
  },
  selectedStudentItem: {
    backgroundColor: colors.backgroundHighlight,
  },
  textPrimaryLarge: {
    fontSize: 16,
    color: colors.textPrimary,
  },
  selectionConfirmation: {
    textAlign: 'center',
    fontStyle: 'italic',
    color: colors.textSecondary,
    marginBottom: 10,
    fontSize: 15,
  },

  rewardItemBase: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
    borderRadius: 6,
    backgroundColor: colors.backgroundPrimary,
  },
  rewardItemUnaffordable: {
    opacity: 0.6,
    backgroundColor: colors.backgroundGrey, // Grey out unaffordable items
  },
  rewardItemSelected: {
    borderColor: colors.success, // Highlight selected item
    borderWidth: 2,
    backgroundColor: colors.backgroundHighlight,
  },
  rewardImage: {
    width: 50,
    height: 50,
    marginRight: 12,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
    backgroundColor: colors.backgroundGrey, // Placeholder bg
  },
  loadingAffordText: {
    fontSize: 12,
    color: colors.textLight,
    fontStyle: 'italic',
    marginTop: 2,
  },

  pinLabel: {
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 5,
    fontWeight: '600',
  },
  pinValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.primary,
    letterSpacing: 3,
    marginBottom: 10,
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
    backgroundColor: colors.backgroundPrimary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
  },
  pinInstructions: {
    fontSize: 13,
    color: colors.textLight,
    textAlign: 'center',
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.backgroundPrimary,
  },
  toggleButtonActive: {
    backgroundColor: colors.primary,
  },
  toggleButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  toggleButtonTextActive: {
    color: colors.textWhite,
  },
  userNameText: {
    fontSize: 18, // Adjust size
    fontWeight: 'bold',
    color: colors.textPrimary,
    flexShrink: 1, // Allow text to shrink if needed
    marginRight: 10, // Space before buttons
  },
  statusText: {
    fontWeight: 'bold',
    // Color is set inline based on status
  },

  headerSection: {
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: 5,
  },
  textWelcome: {
    textAlign: 'center',
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 10,
  },
  goalDetails: {
    flex: 1,
    marginLeft: 10,
  },
});
