import { StyleSheet } from 'react-native';

import { colors } from './colors';

export const appSharedStyles = StyleSheet.create({
  balance: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  container: {
    backgroundColor: colors.backgroundSecondary,
    flex: 1,
    padding: 15,
  },
  contentArea: {
    flex: 1,
  },
  emptyListText: {
    color: colors.textLight,
    fontStyle: 'italic',
    marginTop: 5,
    textAlign: 'center',
  },
  filterAndSearchContainer: {
    marginBottom: 10,
    paddingVertical: 5,
  },
  filterContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginBottom: 10,
  },
  filterLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 10,
  },
  footer: {
    color: colors.textSecondary,
    fontSize: 16,
    marginBottom: 10,
    marginTop: 20,
    textAlign: 'center',
  },
  goalContainer: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderHighlight,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 20,
    padding: 15,
  },
  goalImage: {
    borderColor: colors.borderSecondary,
    borderRadius: 4,
    borderWidth: 1,
    height: 50,
    width: 50,
  },
  goalText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  header: {
    color: colors.textPrimary,
    flexShrink: 1,
    fontSize: 22,
    fontWeight: 'bold',
  },
  headerContainer: {
    alignItems: 'center',
    backgroundColor: colors.backgroundPrimary,
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 5,
    paddingHorizontal: 15,
    paddingTop: 10,
  },
  headerSideContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    minWidth: 60,
  },
  headerTitle: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 22,
    fontWeight: 'bold',
    marginHorizontal: 5,
    textAlign: 'center',
  },
  hidden: {
    display: 'none',
  },
  inactiveItem: {
    borderColor: colors.secondary,
    opacity: 0.7,
  },
  inactiveItemStyle: {
    borderColor: colors.secondary,
    opacity: 0.7,
  },
  instrumentText: {
    color: colors.textSecondary,
    fontSize: 16,
    marginBottom: 5,
  },
  itemContainer: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderSecondary,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  itemDetailText: {
    color: colors.textSecondary,
    fontSize: 13,
    marginBottom: 2,
  },
  itemTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  listArea: {
    marginTop: 10,
  },
  listContentContainer: {
    paddingBottom: 5,
  },
  parentHeader: {
    alignItems: 'center',
    backgroundColor: colors.backgroundPrimary,
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  parentHeaderText: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  pendingItem: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderWarning,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  progressBarBackground: {
    backgroundColor: '#eee',
    borderRadius: 5,
    height: 10,
    marginBottom: 10,
    overflow: 'hidden',
  },
  progressBarFill: {
    borderRadius: 5,
    height: '100%',
  },
  progressText: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 5,
  },
  publicHeader: {
    fontSize: 28,
    marginBottom: 5,
    textAlign: 'center',
  },
  rewardItemAffordable: {
    borderColor: colors.success,
    borderWidth: 2,
  },
  rewardItemGoal: {
    backgroundColor: colors.backgroundHighlight,
    borderColor: colors.primary,
    borderWidth: 2,
  },
  safeArea: {
    backgroundColor: colors.backgroundSecondary,
    flex: 1,
  },
  sectionTitle: {
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    marginTop: 20,
    paddingBottom: 5,
  },
  studentActions: {
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'space-around',
    marginTop: 10,
  },
  subheader: {
    color: colors.textSecondary,
    fontSize: 18,
    marginBottom: 20,
    textAlign: 'center',
  },
  tabContainer: {
    borderBottomColor: colors.borderSecondary,
    borderBottomWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
    marginBottom: 5,
    paddingBottom: 10,
  },
  tabContentPlaceholder: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  taskLibraryItemTickets: {
    color: colors.textSecondary,
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 5,
  },
  teacherNav: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginBottom: 20,
  },
  textDanger: {
    color: colors.danger,
  },
  textGold: {
    color: colors.gold,
  },
  textSuccess: {
    color: colors.success,
  },
  textWarning: {
    color: colors.warning,
  },
});
