import { StyleSheet } from 'react-native';

import { colors } from './colors';

export const appSharedStyles = StyleSheet.create({
  hidden: {
    display: 'none',
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.backgroundSecondary,
  },
  container: {
    flex: 1,
    padding: 15,
    backgroundColor: colors.backgroundSecondary,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderPrimary,
    backgroundColor: colors.backgroundPrimary,
  },
  header: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.textPrimary,
    flexShrink: 1,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 15,
    color: colors.textPrimary,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderPrimary,
    paddingBottom: 5,
  },
  emptyListText: {
    textAlign: 'center',
    color: colors.textLight,
    marginTop: 5,
    fontStyle: 'italic',
  },
  itemContainer: {
    backgroundColor: colors.backgroundPrimary,
    padding: 12,
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 5,
  },
  itemDetailText: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 2,
  },
  textGold: { color: colors.gold },
  textSuccess: { color: colors.success },
  textDanger: { color: colors.danger },
  textWarning: { color: colors.warning },
  inactiveItem: { borderColor: colors.secondary, opacity: 0.7 },
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginBottom: 5,
    gap: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSecondary,
  },
  filterAndSearchContainer: { paddingVertical: 5, marginBottom: 10 },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  filterLabel: { marginRight: 10, fontSize: 14, fontWeight: 'bold', color: colors.textSecondary },
  listArea: { marginTop: 10 },
  taskLibraryItemTickets: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 5,
    fontStyle: 'italic',
  },
  publicHeader: {
    fontSize: 28,
    textAlign: 'center',
    marginBottom: 5,
  },
  subheader: {
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 20,
    color: colors.textSecondary,
  },
  contentArea: {
    flex: 1,
  },
  tabContentPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listContentContainer: {
    paddingBottom: 5,
  },
  footer: {
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 10,
    fontSize: 16,
    color: colors.textSecondary,
  },
  pendingItem: { backgroundColor: colors.backgroundPrimary, padding: 12, marginBottom: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.borderWarning, },    
  headerSideContainer: { minWidth: 60, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', },
  headerTitle: { flex: 1, fontSize: 22, fontWeight: 'bold', color: colors.textPrimary, textAlign: 'center', marginHorizontal: 5, },
  parentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderPrimary,
    backgroundColor: colors.backgroundPrimary,
  },
  parentHeaderText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },  
  rewardItemAffordable: { borderColor: colors.success, borderWidth: 2 },
  rewardItemGoal: {
    borderColor: colors.primary,
    borderWidth: 2,
    backgroundColor: colors.backgroundHighlight,
  },
  instrumentText: { fontSize: 16, color: colors.textSecondary, marginBottom: 5 },
  balance: { fontSize: 28, fontWeight: 'bold', marginBottom: 15 },
  goalContainer: {
    backgroundColor: colors.backgroundPrimary,
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderHighlight,
    marginBottom: 20,
  },
  goalImage: {
    width: 50,
    height: 50,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
  },
  goalText: { fontSize: 16, fontWeight: '600', color: colors.textPrimary },
  progressText: { fontSize: 14, color: colors.textSecondary, marginBottom: 5 },
  progressBarBackground: {
    height: 10,
    backgroundColor: '#eee',
    borderRadius: 5,
    overflow: 'hidden',
    marginBottom: 10,
  },
  progressBarFill: { height: '100%', borderRadius: 5 },
  teacherNav: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 8,
  },
  studentActions: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 10, gap: 5 },
  inactiveItemStyle: { borderColor: colors.secondary, opacity: 0.7 },
});
