// src/styles/commonSharedStyles.ts
import { Platform, StyleSheet } from 'react-native';

import { colors } from './colors';

export const commonSharedStyles = StyleSheet.create({
  activeStatus: {
    fontWeight: 'bold',
    color: colors.success,
  },
  assignedTaskActions: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  awardedPointsText: {
    color: colors.gold,
    fontSize: 20,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  baseAlignCenter: {
    alignItems: 'center',
  },
  baseCentered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  baseColumn: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  baseEmptyText: {
    color: colors.textLight,
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  baseFull: {
    width: '100%',
  },
  baseGap: {
    gap: 5,
  },
  baseGapLarge: {
    gap: 20,
  },
  baseHeaderText: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: 'bold',
  },
  baseHeaderTextLarge: {
    color: colors.textPrimary,
    fontSize: 26,
    fontWeight: 'bold',
  },
  baseIcon: {
    height: 40,
    width: 40,
    marginRight: 10,
    resizeMode: 'contain',
  },
  baseItem: {
    padding: 8,
    borderWidth: 1,
    borderRadius: 8,
    borderColor: colors.borderPrimary,
    backgroundColor: colors.backgroundPrimary,
    marginBottom: 8,
  },
  baseLightText: {
    color: colors.textLight,
    fontSize: 14,
    marginBottom: 4,
  },
  baseMargin: {
    margin: 5,
  },
  baseMarginTopBottom: {
    marginTop: 15,
    marginBottom: 15,
  },
  basePadding: {
    padding: 5,
  },
  baseRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  baseRowCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  baseSecondaryText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  baseSelfAlign: {
    alignSelf: 'flex-start',
  },
  baseSelfAlignCenter: {
    alignSelf: 'center',
  },
  baseSelfAlignStretch: {
    alignSelf: 'stretch',
  },
  baseSubTitleText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '500',
  },
  baseTitleText: {
    color: colors.textPrimary,
    fontSize: 18,
  },
  baseVeryLightText: {
    color: colors.textVeryLight,
    fontSize: 12,
    marginBottom: 4,
  },
  bold: {
    fontWeight: 'bold',
  },
  cannotAffordText: {
    color: colors.textLight,
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 2,
  },
  centeredView: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    flex: 1,
    justifyContent: 'center',
  },
  checkmark: {
    color: colors.success,
    fontSize: 24,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  confirmationText: {
    fontSize: 16,
    lineHeight: 22,
    marginVertical: 15,
    textAlign: 'center',
  },
  containerIconPreview: {
    alignItems: 'center',
    marginBottom: 15,
    paddingBottom: 15,
    width: '100%',
    gap: 10,
  },
  containerPinDisplay: {
    alignItems: 'center',
    backgroundColor: colors.backgroundHighlight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderPrimary,
    padding: 15,
    marginVertical: 15,
  },
  containerToggle: {
    flexDirection: 'row',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 6,
    overflow: 'hidden',
  },
  currentGoalItem: {
    backgroundColor: colors.backgroundHighlight,
    borderColor: colors.primary,
    borderWidth: 2,
  },
  errorContainer: {
    alignItems: 'center',
    backgroundColor: '#ffebee',
    borderColor: colors.danger,
    borderRadius: 5,
    borderWidth: 1,
    marginVertical: 15,
    padding: 15,
    width: '100%',
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    textAlign: 'center',
  },
  filterLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 10,
    minWidth: 90,
    textAlign: 'right',
  },
  filterSection: {
    borderBottomColor: colors.borderSecondary,
    borderBottomWidth: 1,
    paddingBottom: 10,
    marginBottom: 10,
    width: '100%',
    gap: 10,
  },
  flex0: {
    flex: 0,
  },
  flex1: {
    flex: 1,
  },
  flexGrow: {
    flexGrow: 1,
  },
  full: {
    width: '100%',
    gap: 8,
  },
  goalImage: {
    borderColor: colors.borderSecondary,
    borderRadius: 4,
    borderWidth: 1,
    height: 50,
    width: 50,
  },
  goalSelectDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  goalSelectImage: {
    borderColor: colors.borderSecondary,
    borderRadius: 4,
    borderWidth: 1,
    height: 45,
    marginRight: 12,
    width: 45,
  },
  goalSelectItem: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderSecondary,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  goalSelectItemContent: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  goalSelectName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 2,
  },
  iconPreview: {
    width: 80,
    height: 80,
    marginBottom: 5,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
    backgroundColor: colors.backgroundGrey,
  },
  inactiveItem: {
    borderColor: colors.secondary,
    opacity: 0.7,
  },
  inactiveStatus: {
    fontWeight: 'bold',
    color: colors.secondary,
  },
  infoText: {
    fontSize: 12,
    color: colors.textLight,
    fontStyle: 'italic',
    marginTop: 2,
    marginLeft: 5,
    textAlign: 'center',
    marginBottom: 10,
  },
  input: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderPrimary,
    borderRadius: 5,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 16,
    marginBottom: 15,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: '100%',
    minHeight: 40,
  },
  itemImageMedium: {
    borderColor: colors.borderPrimary,
    borderRadius: 4,
    borderWidth: 1,
    height: 60,
    width: 60,
    marginRight: 15,
  },
  itemTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  justifyCenter: {
    justifyContent: 'center',
  },
  justifyFlexEnd: {
    justifyContent: 'flex-end',
  },
  justifyFlexStart: {
    justifyContent: 'flex-start',
  },
  justifySpaceBetween: {
    justifyContent: 'space-between',
  },
  label: {
    alignSelf: 'flex-start',
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
    width: '100%',
  },
  linkedStudentItem: {
    backgroundColor: colors.backgroundGrey,
  },
  linkText: {
    color: colors.primary,
    textDecorationLine: 'underline',
    fontWeight: '600',
  },
  listArea: {
    marginTop: 10,
    width: '100%',
  },
  listItem: {
    borderBottomColor: colors.borderSecondary,
    borderBottomWidth: 1,
    padding: 12,
  },
  listItemFull: {
    flexGrow: 0,
    marginBottom: 15,
    maxHeight: Platform.OS === 'web' ? 400 : 300,
    width: '100%',
    borderWidth: 1,
    borderColor: colors.borderSecondary,
    borderRadius: 5,
  },
  listItemText: {
    color: colors.textPrimary,
    fontSize: 15,
  },
  loadingAffordText: {
    fontSize: 12,
    color: colors.textLight,
    fontStyle: 'italic',
    marginTop: 2,
  },
  modalContextInfo: {
    color: colors.textSecondary,
    fontSize: 15,
    marginBottom: 10,
    textAlign: 'center',
    width: '100%',
  },
  modalFooter: {
    width: '100%',
    gap: 10,
  },
  modalHeader: {
    alignItems: 'center',
    backgroundColor: colors.backgroundPrimary,
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    padding: 15,
    width: '100%',
  },
  modalMessage: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 21,
    marginBottom: 25,
    textAlign: 'center',
  },
  modalScrollView: {
    marginBottom: 15,
    width: '100%',
    flexGrow: 0,
  },
  modalSectionTitle: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
    marginTop: 15,
    textAlign: 'center',
    width: '100%',
  },
  modalStepTitle: {
    alignSelf: 'flex-start',
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
    marginTop: 10,
    width: '100%',
  },
  modalSubSection: {
    borderTopColor: colors.borderSecondary,
    borderTopWidth: 1,
    marginTop: 20,
    paddingTop: 15,
    width: '100%',
  },
  modalSubTitle: {
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 15,
    paddingBottom: 10,
    textAlign: 'center',
    width: '100%',
  },
  modalTitle: {
    borderBottomColor: colors.borderPrimary,
    borderBottomWidth: 1,
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    paddingBottom: 10,
    textAlign: 'center',
    width: '100%',
  },
  modalView: {
    alignItems: 'stretch',
    backgroundColor: colors.backgroundPrimary,
    borderRadius: 10,
    elevation: 5,
    margin: 20,
    maxHeight: '90%',
    maxWidth: 500,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    width: '90%',
  },
  pageInfo: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    marginHorizontal: 15,
  },
  paginationContainer: {
    alignItems: 'center',
    borderTopColor: colors.borderSecondary,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    marginTop: 10,
  },
  pendingDetail: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 3,
  },
  pendingItem: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderWarning,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  pendingNote: {
    color: colors.warning,
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 5,
  },
  pendingTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  picker: {
    width: '100%',
    height: Platform.OS === 'android' ? 50 : undefined,
    color: colors.textPrimary,
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderPrimary,
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 15,
  },
  pickerItem: {
    height: Platform.OS === 'ios' ? 120 : 40,
    fontSize: 16,
    color: colors.textPrimary,
  },
  pinInstructions: {
    fontSize: 13,
    color: colors.textLight,
    textAlign: 'center',
  },
  pinLabel: {
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 5,
    fontWeight: '600',
  },
  pinValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.primary,
    letterSpacing: 3,
    marginBottom: 10,
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
    backgroundColor: colors.backgroundPrimary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
  },
  previewText: {
    color: colors.textLight,
    fontSize: 14,
    fontStyle: 'italic',
    marginBottom: 15,
    textAlign: 'center',
    marginTop: 5,
  },
  progressBarBackground: {
    backgroundColor: '#eee',
    borderRadius: 5,
    height: 10,
    marginBottom: 10,
    overflow: 'hidden',
    width: '100%',
  },
  progressBarFill: {
    borderRadius: 5,
    height: '100%',
  },
  rangeText: {
    color: colors.textSecondary,
    flexDirection: 'row',
    fontSize: 12,
    justifyContent: 'space-between',
    marginBottom: 15,
    marginTop: -5,
    paddingHorizontal: 5,
    width: '100%',
  },
  rewardImage: {
    width: 50,
    height: 50,
    marginRight: 12,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
    backgroundColor: colors.backgroundGrey,
  },
  rewardItemAffordable: {
    borderColor: colors.success,
    borderWidth: 2,
  },
  rewardItemBase: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
    borderRadius: 6,
    backgroundColor: colors.backgroundPrimary,
    marginBottom: 8,
  },
  rewardItemGoal: {
    backgroundColor: colors.backgroundHighlight,
    borderColor: colors.primary,
    borderWidth: 2,
  },
  rewardItemSelected: {
    borderColor: colors.success,
    borderWidth: 2,
    backgroundColor: colors.backgroundHighlight,
  },
  rewardItemUnaffordable: {
    opacity: 0.6,
    backgroundColor: colors.backgroundGrey,
  },
  rewardName: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  roleSectionTitle: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  roleSpecificSection: {
    borderTopColor: colors.borderSecondary,
    borderTopWidth: 1,
    marginTop: 15,
    paddingTop: 15,
    width: '100%',
  },
  searchInput: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderPrimary,
    borderRadius: 5,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 16,
    marginBottom: 10,
    padding: 10,
    width: '100%',
  },
  selectionConfirmation: {
    textAlign: 'center',
    fontStyle: 'italic',
    color: colors.textSecondary,
    marginBottom: 10,
    marginTop: 10,
    fontSize: 15,
  },
  selectedStudentItem: {
    backgroundColor: colors.backgroundHighlight,
    padding: 10,
    borderRadius: 5,
  },
  separator: {
    backgroundColor: colors.borderSecondary,
    height: 1,
    marginVertical: 10,
  },
  slider: {
    height: 40,
    marginTop: 10,
    width: '100%',
  },
  statusText: {
    fontWeight: 'bold',
  },
  taskItemStatus: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 4,
  },
  taskItemTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  taskLibraryItemTickets: {
    color: colors.textSecondary,
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 5,
  },
  textArea: {
    backgroundColor: colors.backgroundPrimary,
    borderColor: colors.borderPrimary,
    borderRadius: 5,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 16,
    marginBottom: 15,
    minHeight: 80,
    paddingHorizontal: 10,
    paddingVertical: 8,
    textAlignVertical: 'top',
    width: '100%',
  },
  textCenter: {
    textAlign: 'center',
  },
  textDanger: {
    color: colors.danger,
  },
  textGold: {
    color: colors.gold,
  },
  textPrimaryLarge: {
    fontSize: 16,
    color: colors.textPrimary,
  },
  textSuccess: {
    color: colors.success,
  },
  textWarning: {
    color: colors.warning,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.backgroundPrimary,
  },
  toggleButtonActive: {
    backgroundColor: colors.primary,
  },
  toggleButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  toggleButtonTextActive: {
    color: colors.textWhite,
  },
});
