// src/styles/commonSharedStyles.ts
import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const commonSharedStyles = StyleSheet.create({
  label: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
    color: colors.textPrimary,
    alignSelf: 'flex-start', // Usually labels align left
    width: '100%', // Take full width for consistency
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: colors.borderPrimary,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 16,
    color: colors.textPrimary,
    backgroundColor: colors.backgroundPrimary,
    marginBottom: 15,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
    width: '100%',
    borderWidth: 1,
    borderColor: colors.borderPrimary,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 16,
    color: colors.textPrimary,
    backgroundColor: colors.backgroundPrimary,
    marginBottom: 15,
  },
  separator: {
      height: 1,
      backgroundColor: colors.borderSecondary,
      marginVertical: 10,
  },
  selectionContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginBottom: 10,
    width: '100%',
  },
  errorContainer: {
    marginVertical: 20,
    padding: 15,
    alignItems: 'center',
    backgroundColor: '#ffebee',
    borderColor: colors.danger,
    borderWidth: 1,
    borderRadius: 5,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    textAlign: 'center',
  },  
  itemContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  itemImageMedium: {
    width: 60,
    height: 60,
    marginRight: 15,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.borderPrimary,
  },
  itemDetailsContainer: {
    flex: 1,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 10,
    marginTop: 15,
    marginBottom: 15,
  },    
  searchInput: {
    height: 40,
    borderColor: colors.borderPrimary,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    fontSize: 15,
    backgroundColor: colors.backgroundPrimary,
    color: colors.textPrimary,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 10,
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.borderSecondary,
  },
  pageInfo: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
    marginHorizontal: 15,
  },
  rewardName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  announcementTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  announcementDate: {
    fontSize: 12,
    color: colors.textVeryLight,
    marginTop: 8,
    textAlign: 'right',
  },
  taskItemStatus: { fontSize: 14, color: colors.textSecondary, marginBottom: 8 },
  pendingNote: { fontSize: 13, color: colors.warning, fontStyle: 'italic', marginTop: 5 },
  historyItemContainer: {
    backgroundColor: colors.backgroundGrey,
    padding: 10,
    marginBottom: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
  },
  historyItemTimestamp: { fontSize: 12, color: colors.textVeryLight, marginBottom: 4 },
  historyItemDetails: { fontSize: 14, color: colors.textSecondary },
  historyItemAmount: { fontWeight: 'bold' },
  historyItemNotes: { fontSize: 13, color: colors.textLight, marginTop: 4, fontStyle: 'italic' },
});